export enum EPossibleRelicStats {
  atk = "atk",
  atkPercentage = "atkPercentage",
  hp = "hp",
  hpPercentage = "hpPercentage",
  def = "def",
  defPercentage = "defPercentage",
  spd = "spd",
  critRate = "critRate",
  critDmg = "critDmg",
  effectHitRate = "effectHitRate",
  effectResistance = "effectResistance",
  breakEffect = "breakEffect",
  dmgBonus = "dmgBonus",
  energyRegenerationRate = "energyRegenerationRate",
  outgoingHealingBoost = "outgoingHealingBoost",
}
